micronaut:
  application:
    name: micronautCloudReady
  server:
    thread-selection: auto
    port: ${MICRONAUT_PORT:`8080`}
    max-request-size: ${MICRONAUT_SERVER_MAX_REQUEST_SIZE:`1024`}
  metrics:
    enabled: ${MICRONAUT_METRICS_ENABLED:true}
    export:
      prometheus:
        enabled: true
        step: PT30s
        descriptions: false

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
  metrics:
    enabled: ${MICRONAUT_METRICS_ENABLED:true}
    sensitive: false
  prometheus:
    enabled: true
    sensitive: false
  loggers:
    enabled: true
    sensitive: false
    write-sensitive: false
