apiVersion: v1
kind: ConfigMap
metadata:
  name: micronaut-cloud-ready
  labels:
    app: micronaut-cloud-ready
    env: dev
data:
  # property-like keys; each key maps to a simple value
  micronaut.port: "8080"
  micronaut.server.max-request-size: "10mb"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micronaut-cloud-ready
  labels:
    app: micronaut-cloud-ready
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micronaut-cloud-ready
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1 # In production deployment you will want, at least, 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: micronaut-cloud-ready
    spec:
      containers:
        - name: micronaut-cloud-ready
          image: micronaut-cloud-ready:latest
          imagePullPolicy: Never # The value Never is good for minikube on development stage. Going to production, you want to change this to Always o other values
          ports:
            - containerPort: 8080
          env:
            - name: MICRONAUT_PORT
              valueFrom:
                configMapKeyRef:
                  name: micronaut-cloud-ready
                  key: micronaut.port
            - name: MICRONAUT_SERVER_MAX_REQUEST_SIZE
              valueFrom:
                configMapKeyRef:
                  name: micronaut-cloud-ready
                  key: micronaut.server.max-request-size
---
apiVersion: v1
kind: Service
metadata:
  name: micronaut-cloud-ready
  labels:
    app: micronaut-cloud-ready
    env: dev
spec:
  selector:
    app: micronaut-cloud-ready
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: micronaut-cloud-ready
  type: LoadBalancer # We are exposing the service outside of the Kubernetes network